import { ModuleMenuConfig } from '@/shared/types/menu-config.types';

/**
 * Grades Module Menu Configuration
 *
 * This file defines all menu items for the Grades module.
 */
export const gradesMenuConfig: ModuleMenuConfig = {
  module: 'Grades',
  menus: [
    {
      id: 'grades',
      label: 'Grades & Evaluations',
      route: '/admin/grades',
      icon: {
        type: 'emoji',
        value: '📝',
      },
      order: 25,
      module: 'Grades',
      roles: ['admin', 'superadmin', 'teacher', 'enseignant'],
      isVisible: true,
      isActive: true,
      children: [
        {
          id: 'grades-entry',
          label: 'Grade Entry',
          route: '/admin/grades/entry',
          icon: {
            type: 'emoji',
            value: '✏️',
          },
          order: 1,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin', 'teacher', 'enseignant'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-validations',
          label: 'Grade Validation',
          route: '/admin/grades/validations',
          icon: {
            type: 'emoji',
            value: '✅',
          },
          order: 1.5,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin', 'responsable_pedagogique'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-coefficients',
          label: 'Coefficients & ECTS',
          route: '/admin/grades/coefficients',
          icon: {
            type: 'emoji',
            value: '⚖️',
          },
          order: 2,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-eliminatory',
          label: 'Eliminatory Modules',
          route: '/admin/grades/eliminatory',
          icon: {
            type: 'emoji',
            value: '⚠️',
          },
          order: 2.5,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-module-results',
          label: 'Module Results',
          route: '/admin/grades/module-results',
          icon: {
            type: 'emoji',
            value: '📊',
          },
          order: 2.6,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-semester-results',
          label: 'Semester Results',
          route: '/admin/grades/semester-results',
          icon: {
            type: 'emoji',
            value: '📋',
          },
          order: 2.7,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-compensation',
          label: 'Compensation',
          route: '/admin/grades/compensation',
          icon: {
            type: 'emoji',
            value: '🔄',
          },
          order: 2.75,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-ects',
          label: 'ECTS Credits',
          route: '/admin/grades/ects',
          icon: {
            type: 'emoji',
            value: '🎓',
          },
          order: 2.8,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-deliberation',
          label: 'Deliberations',
          route: '/admin/grades/deliberation',
          icon: {
            type: 'emoji',
            value: '🏛️',
          },
          order: 3,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-publications',
          label: 'Publications',
          route: '/admin/grades/publications',
          icon: {
            type: 'emoji',
            value: '📢',
          },
          order: 3.5,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-retakes',
          label: 'Rattrapages',
          route: '/admin/grades/retakes',
          icon: {
            type: 'emoji',
            value: '🔁',
          },
          order: 3.6,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-retake-entry',
          label: 'Saisie Rattrapage',
          route: '/admin/grades/retake-entry',
          icon: {
            type: 'emoji',
            value: '✍️',
          },
          order: 3.7,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin', 'teacher', 'enseignant'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-retake-recalculation',
          label: 'Recalcul Rattrapage',
          route: '/admin/grades/retake-recalculation',
          icon: {
            type: 'emoji',
            value: '🔢',
          },
          order: 3.8,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-final-results',
          label: 'Résultats Finaux',
          route: '/admin/grades/final-results',
          icon: {
            type: 'emoji',
            value: '🏆',
          },
          order: 3.9,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-transcripts',
          label: 'Transcripts',
          route: '/admin/grades/transcripts',
          icon: {
            type: 'emoji',
            value: '📄',
          },
          order: 4,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-statistics',
          label: 'Statistiques Réussite',
          route: '/admin/grades/statistics',
          icon: {
            type: 'emoji',
            value: '📊',
          },
          order: 5,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-rankings',
          label: 'Classements',
          route: '/admin/grades/rankings',
          icon: {
            type: 'emoji',
            value: '🏅',
          },
          order: 5.1,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-pv-deliberation',
          label: 'PV Délibération',
          route: '/admin/grades/pv-deliberation',
          icon: {
            type: 'emoji',
            value: '📜',
          },
          order: 5.2,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-analytics',
          label: 'Analyses Performance',
          route: '/admin/grades/analytics',
          icon: {
            type: 'emoji',
            value: '📈',
          },
          order: 5.3,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'grades-correction-requests',
          label: 'Correction Requests',
          route: '/admin/grades/correction-requests',
          icon: {
            type: 'emoji',
            value: '🔄',
          },
          order: 6,
          module: 'Grades',
          parentId: 'grades',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
      ],
    },
  ],
};
