import { ModuleMenuConfig } from '@/shared/types/menu-config.types';

/**
 * Portail Étudiant — sidebar Étudiant (Stories Étudiant 01-08).
 * Items strictement réservés au rôle `Étudiant` — n'apparaissent pas
 * dans la sidebar de l'Administrator. Story 09 (LMD transferts) exclue V1.
 */
export const portailEtudiantMenuConfig: ModuleMenuConfig = {
  module: 'PortailEtudiant',
  menus: [
    {
      id: 'student-home',
      label: 'Accueil',
      route: '/admin/student/home',
      icon: { type: 'emoji', value: '🏠' },
      order: 5,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-grades',
      label: 'Mes notes',
      route: '/admin/student/my-grades',
      icon: { type: 'emoji', value: '📊' },
      order: 10,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-timetable',
      label: 'Mon emploi du temps',
      route: '/admin/student/my-timetable',
      icon: { type: 'emoji', value: '📅' },
      order: 20,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-attendance',
      label: 'Mes présences',
      route: '/admin/student/my-attendance',
      icon: { type: 'emoji', value: '✅' },
      order: 30,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-invoices',
      label: 'Mes factures',
      route: '/admin/student/my-invoices',
      icon: { type: 'emoji', value: '💰' },
      order: 40,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-documents',
      label: 'Mes documents',
      route: '/admin/student/my-documents',
      icon: { type: 'emoji', value: '📄' },
      order: 50,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-card',
      label: 'Ma carte scolaire',
      route: '/admin/student/my-card',
      icon: { type: 'emoji', value: '🪪' },
      order: 60,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
    {
      id: 'student-reenrollment',
      label: 'Réinscription',
      route: '/admin/student/reenrollment',
      icon: { type: 'emoji', value: '🔄' },
      order: 70,
      module: 'PortailEtudiant',
      roles: ['admin'],
      requiredRoles: ['Étudiant'],
      isVisible: true,
      isActive: true,
    },
  ],
};
