'use client';

import { useState, useEffect } from 'react';
import { useTranslation } from '@/shared/i18n/use-translation';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Alert from '@mui/material/Alert';
import CircularProgress from '@mui/material/CircularProgress';
import Autocomplete from '@mui/material/Autocomplete';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import { useStudentsContext } from './StudentList';
import { studentService } from '../services/studentService';
import type { Student, StudentFormData, Sex } from '../../types/student.types';
import type { Programme } from '@/modules/StructureAcademique/types/programme.types';

interface StudentFormDialogProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  student?: Student | null;
  isEditMode?: boolean;
}

const getSexOptions = (t: (key: string) => string): { value: Sex; label: string }[] => [
  { value: 'M', label: t('Male') },
  { value: 'F', label: t('Female') },
  { value: 'O', label: t('Other') },
];

export const StudentFormDialog = ({
  open,
  onClose,
  onSuccess,
  student,
  isEditMode = false,
}: StudentFormDialogProps) => {
  const { t } = useTranslation('Enrollment');
  const { createStudent, updateStudent, loading, programmes, loadingProgrammes } =
    useStudentsContext();
  const [error, setError] = useState<string | null>(null);
  const [selectedProgramme, setSelectedProgramme] = useState<Programme | null>(null);
  const [duplicateWarning, setDuplicateWarning] = useState<string | null>(null);

  const [formData, setFormData] = useState<StudentFormData>({
    firstname: '',
    lastname: '',
    birthdate: '',
    birthplace: '',
    sex: 'M',
    email: '',
    phone: '',
    mobile: '',
    address: '',
    city: '',
    country: 'Niger',
    nationality: 'Nigérienne',
    emergency_contact_name: '',
    emergency_contact_phone: '',
    programme_id: 0,
  });

  // Initialize form data when student changes
  useEffect(() => {
    if (student && isEditMode) {
      setFormData({
        firstname: student.firstname,
        lastname: student.lastname,
        birthdate: student.birthdate,
        birthplace: student.birthplace,
        sex: student.sex,
        email: student.email,
        phone: student.phone || '',
        mobile: student.mobile,
        address: student.address || '',
        city: student.city || '',
        country: student.country,
        nationality: student.nationality,
        emergency_contact_name: student.emergency_contact_name || '',
        emergency_contact_phone: student.emergency_contact_phone || '',
        programme_id: 0, // Not used in edit mode
      });

      // Don't set selected programme in edit mode (not editable)
      setSelectedProgramme(null);
    } else {
      // Reset form for add mode
      setFormData({
        firstname: '',
        lastname: '',
        birthdate: '',
        birthplace: '',
        sex: 'M',
        email: '',
        phone: '',
        mobile: '',
        address: '',
        city: '',
        country: 'Niger',
        nationality: 'Nigérienne',
        emergency_contact_name: '',
        emergency_contact_phone: '',
        programme_id: 0,
      });
      setSelectedProgramme(null);
      setDuplicateWarning(null);
    }
    setError(null);
  }, [student, isEditMode, programmes]);

  const handleChange = (field: keyof StudentFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    setError(null);
  };

  const handleProgrammeChange = (programme: Programme | null) => {
    setSelectedProgramme(programme);
    if (programme) {
      setFormData(prev => ({ ...prev, programme_id: programme.id }));
    }
  };

  const validateForm = (): boolean => {
    // Required fields validation
    if (!formData.firstname.trim()) {
      setError(t('First name is required'));

      return false;
    }
    if (!formData.lastname.trim()) {
      setError(t('Last name is required'));

      return false;
    }
    if (!formData.birthdate) {
      setError(t('Birth date is required'));

      return false;
    }
    if (!formData.birthplace.trim()) {
      setError(t('Birthplace is required'));

      return false;
    }
    if (!formData.email.trim()) {
      setError(t('Email is required'));

      return false;
    }
    if (!formData.mobile.trim()) {
      setError(t('Mobile phone is required'));

      return false;
    }

    // Programme is no longer required - matricule is auto-generated by backend

    // Email format validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!emailRegex.test(formData.email)) {
      setError(t('Invalid email format'));

      return false;
    }

    // Phone format validation (international format)
    const phoneRegex = /^\+\d{10,15}$/;

    if (formData.mobile && !phoneRegex.test(formData.mobile)) {
      setError(t('Mobile must be in international format (+227...)'));

      return false;
    }

    if (formData.phone && !phoneRegex.test(formData.phone)) {
      setError(t('Phone must be in international format (+227...)'));

      return false;
    }

    return true;
  };

  const handleSubmit = async () => {
    setError(null);
    setDuplicateWarning(null);

    if (!validateForm()) {
      return;
    }

    try {
      if (isEditMode && student) {
        await updateStudent(student.id, formData);
      } else {
        // Check for duplicates before creating
        const duplicateResult = await studentService.checkDuplicates({
          firstname: formData.firstname,
          lastname: formData.lastname,
          birthdate: formData.birthdate,
        });

        if (duplicateResult.has_duplicates && duplicateResult.potential_duplicates.length > 0) {
          setDuplicateWarning(
            t('Warning: {{count}} similar student(s) found. Do you want to continue?', { count: duplicateResult.potential_duplicates.length })
          );

          return;
        }

        await createStudent(formData);
      }

      onSuccess();
      handleClose();
    } catch (err: any) {
      const errorMessage = err.response?.data?.message || err.message || t('An error occurred');

      setError(errorMessage);
      console.error('Error saving student:', err);
    }
  };

  const handleClose = () => {
    setFormData({
      firstname: '',
      lastname: '',
      birthdate: '',
      birthplace: '',
      sex: 'M',
      email: '',
      phone: '',
      mobile: '',
      address: '',
      city: '',
      country: 'Niger',
      nationality: 'Nigérienne',
      emergency_contact_name: '',
      emergency_contact_phone: '',
      programme_id: 0,
    });
    setSelectedProgramme(null);
    setError(null);
    setDuplicateWarning(null);
    onClose();
  };

  const sexOptions = getSexOptions(t);

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="md" fullWidth>
      <DialogTitle>
        {isEditMode ? t('Edit student') : t('Add student')}
        {isEditMode && student && (
          <Typography variant="caption" display="block" color="text.secondary">
            {t('Matricule')}: {student.matricule}
          </Typography>
        )}
      </DialogTitle>
      <DialogContent>
        <Box sx={{ mt: 2 }}>
          {error && (
            <Alert severity="error" sx={{ mb: 2 }}>
              {error}
            </Alert>
          )}
          {duplicateWarning && (
            <Alert severity="warning" sx={{ mb: 2 }}>
              {duplicateWarning}
            </Alert>
          )}

          <Grid container spacing={2}>
            {/* Personal Information Section */}
            <Grid item xs={12}>
              <Typography variant="subtitle1" fontWeight="bold" gutterBottom>
                {t('Personal Information')}
              </Typography>
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                required
                label={t('First name(s)')}
                value={formData.firstname}
                onChange={e => handleChange('firstname', e.target.value)}
                disabled={loading}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                required
                label={t('Last name')}
                value={formData.lastname}
                onChange={e => handleChange('lastname', e.target.value)}
                disabled={loading}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                required
                type="date"
                label={t('Birth date')}
                value={formData.birthdate}
                onChange={e => handleChange('birthdate', e.target.value)}
                disabled={loading}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                required
                label={t('Birthplace')}
                value={formData.birthplace}
                onChange={e => handleChange('birthplace', e.target.value)}
                disabled={loading}
              />
            </Grid>

            <Grid item xs={12} sm={4}>
              <TextField
                fullWidth
                required
                select
                label={t('Sex')}
                value={formData.sex}
                onChange={e => handleChange('sex', e.target.value)}
                disabled={loading}
              >
                {sexOptions.map(option => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>
            </Grid>

            <Grid item xs={12} sm={8}>
              <TextField
                fullWidth
                label={t('Nationality')}
                value={formData.nationality}
                onChange={e => handleChange('nationality', e.target.value)}
                disabled={loading}
              />
            </Grid>

            {/* Contact Information Section */}
            <Grid item xs={12}>
              <Typography variant="subtitle1" fontWeight="bold" gutterBottom sx={{ mt: 2 }}>
                {t('Contact Information')}
              </Typography>
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                required
                type="email"
                label={t('Email')}
                value={formData.email}
                onChange={e => handleChange('email', e.target.value)}
                disabled={loading}
                helperText={t('Format: email@example.com')}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                required
                label={t('Mobile Phone')}
                value={formData.mobile}
                onChange={e => handleChange('mobile', e.target.value)}
                disabled={loading}
                helperText={t('International format: +227...')}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label={t('Landline Phone')}
                value={formData.phone}
                onChange={e => handleChange('phone', e.target.value)}
                disabled={loading}
                helperText={t('International format: +227...')}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label={t('City')}
                value={formData.city}
                onChange={e => handleChange('city', e.target.value)}
                disabled={loading}
              />
            </Grid>

            <Grid item xs={12}>
              <TextField
                fullWidth
                label={t('Address')}
                value={formData.address}
                onChange={e => handleChange('address', e.target.value)}
                disabled={loading}
                multiline
                rows={2}
              />
            </Grid>

            {/* Emergency Contact Section */}
            <Grid item xs={12}>
              <Typography variant="subtitle1" fontWeight="bold" gutterBottom sx={{ mt: 2 }}>
                {t('Emergency Contact')}
              </Typography>
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label={t('Contact name')}
                value={formData.emergency_contact_name}
                onChange={e => handleChange('emergency_contact_name', e.target.value)}
                disabled={loading}
              />
            </Grid>

            <Grid item xs={12} sm={6}>
              <TextField
                fullWidth
                label={t('Contact phone')}
                value={formData.emergency_contact_phone}
                onChange={e => handleChange('emergency_contact_phone', e.target.value)}
                disabled={loading}
                helperText={t('International format: +227...')}
              />
            </Grid>

            {/* Info - matricule auto-generated */}
            {!isEditMode && (
              <Grid item xs={12}>
                <Alert severity="info" sx={{ mt: 2 }}>
                  {t('Le matricule sera généré automatiquement lors de la création.')}
                </Alert>
              </Grid>
            )}
          </Grid>
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose} disabled={loading}>
          {t('Cancel')}
        </Button>
        <Button onClick={handleSubmit} variant="contained" disabled={loading}>
          {loading ? <CircularProgress size={24} /> : isEditMode ? t('Edit') : t('Create')}
        </Button>
      </DialogActions>
    </Dialog>
  );
};
