import { ModuleMenuConfig } from '@/shared/types/menu-config.types';

/**
 * Enrollment Module Menu Configuration
 *
 * This file defines all menu items for the Enrollment module.
 */
export const enrollmentMenuConfig: ModuleMenuConfig = {
  module: 'Enrollment',
  menus: [
    {
      id: 'enrollment',
      label: 'Enrollments',
      route: '/admin/enrollment',
      icon: {
        type: 'emoji',
        value: '📝',
      },
      order: 20,
      module: 'Enrollment',
      roles: ['admin', 'superadmin', 'agent_inscription'],
      isVisible: true,
      isActive: true,
      children: [
        {
          id: 'enrollment-students',
          label: 'Students',
          route: '/admin/enrollment/students',
          icon: {
            type: 'emoji',
            value: '👨‍🎓',
          },
          order: 1,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin', 'agent_inscription'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-groups',
          label: 'Group Assignment',
          route: '/admin/enrollment/groups',
          icon: {
            type: 'emoji',
            value: '👥',
          },
          order: 4,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-statistics',
          label: 'Statistics',
          route: '/admin/enrollment/statistics',
          icon: {
            type: 'emoji',
            value: '📊',
          },
          order: 5,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-options',
          label: 'Option Choices',
          route: '/admin/enrollment/options',
          icon: {
            type: 'emoji',
            value: '🎯',
          },
          order: 6,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin', 'agent_inscription'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-validation',
          label: 'Enrollment Validation',
          route: '/admin/enrollment/validation',
          icon: {
            type: 'emoji',
            value: '✅',
          },
          order: 7,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-student-cards',
          label: 'Student Cards',
          route: '/admin/enrollment/student-cards',
          icon: {
            type: 'emoji',
            value: '🪪',
          },
          order: 8,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-reenrollment-campaigns',
          label: 'Re-enrollment Campaigns',
          route: '/admin/enrollment/reenrollment-campaigns',
          icon: {
            type: 'emoji',
            value: '📅',
          },
          order: 9,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-reenrollments',
          label: 'Re-enrollments',
          route: '/admin/enrollment/reenrollments',
          icon: {
            type: 'emoji',
            value: '🔄',
          },
          order: 10,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin', 'agent_inscription'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-transfers',
          label: 'Transfers & Equivalences',
          route: '/admin/enrollment/transfers',
          icon: {
            type: 'emoji',
            value: '🔀',
          },
          order: 11,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'enrollment-exemptions',
          label: 'Module Exemptions',
          route: '/admin/enrollment/exemptions',
          icon: {
            type: 'emoji',
            value: '📋',
          },
          order: 12,
          module: 'Enrollment',
          parentId: 'enrollment',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
      ],
    },
  ],
};
