import type { ModuleMenuConfig } from '@/shared/types/menu-config.types';

/**
 * Timetable Module Menu Configuration
 */
export const timetableMenuConfig: ModuleMenuConfig = {
  module: 'Timetable',
  menus: [
    {
      id: 'timetable',
      label: 'Emplois du Temps',
      route: '/admin/timetable',
      icon: {
        type: 'emoji',
        value: '📅',
      },
      order: 30,
      module: 'Timetable',
      roles: ['admin', 'superadmin'],
      isVisible: true,
      isActive: true,
      children: [
        {
          id: 'timetable-schedule',
          label: 'Planification',
          route: '/admin/timetable/schedule',
          icon: {
            type: 'emoji',
            value: '🗓️',
          },
          order: 1,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-rooms',
          label: 'Gestion des Salles',
          route: '/admin/timetable/rooms',
          icon: {
            type: 'emoji',
            value: '🏫',
          },
          order: 2,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-optimization',
          label: 'Optimisation Auto',
          route: '/admin/timetable/optimization',
          icon: {
            type: 'emoji',
            value: '🤖',
          },
          order: 3,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-duplication',
          label: 'Duplication Semestre',
          route: '/admin/timetable/duplication',
          icon: {
            type: 'emoji',
            value: '📋',
          },
          order: 4,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-exceptions',
          label: 'Modifications Ponctuelles',
          route: '/admin/timetable/exceptions',
          icon: {
            type: 'emoji',
            value: '⚡',
          },
          order: 5,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-group-view',
          label: 'EDT par Groupe',
          route: '/admin/timetable/group-view',
          icon: {
            type: 'emoji',
            value: '👥',
          },
          order: 6,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-teacher-view',
          label: 'EDT Enseignant',
          route: '/admin/timetable/teacher-view',
          icon: {
            type: 'emoji',
            value: '👨‍🏫',
          },
          order: 7,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-room-occupation',
          label: 'Occupation Salles',
          route: '/admin/timetable/room-occupation',
          icon: {
            type: 'emoji',
            value: '📊',
          },
          order: 8,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-student-view',
          label: 'EDT Étudiant',
          route: '/admin/timetable/student-view',
          icon: {
            type: 'emoji',
            value: '🎓',
          },
          order: 9,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-notifications',
          label: 'Centre de Notifications',
          route: '/admin/timetable/notifications',
          icon: {
            type: 'emoji',
            value: '🔔',
          },
          order: 10,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-cancellations',
          label: 'Annulations',
          route: '/admin/timetable/cancellations',
          icon: {
            type: 'emoji',
            value: '🚫',
          },
          order: 11,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-replacements',
          label: 'Remplacements',
          route: '/admin/timetable/replacements',
          icon: {
            type: 'emoji',
            value: '🔄',
          },
          order: 12,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-reminders',
          label: 'Rappels',
          route: '/admin/timetable/reminders',
          icon: {
            type: 'emoji',
            value: '⏰',
          },
          order: 13,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-pdf-export',
          label: 'Export PDF',
          route: '/admin/timetable/pdf-export',
          icon: {
            type: 'emoji',
            value: '📄',
          },
          order: 14,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-occupancy-stats',
          label: 'Statistiques Occupation',
          route: '/admin/timetable/occupancy-stats',
          icon: {
            type: 'emoji',
            value: '📈',
          },
          order: 15,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-teacher-workload',
          label: 'Charges Enseignants',
          route: '/admin/timetable/teacher-workload',
          icon: {
            type: 'emoji',
            value: '👨‍🏫',
          },
          order: 16,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
        {
          id: 'timetable-room-utilization',
          label: 'Utilisation Salles',
          route: '/admin/timetable/room-utilization',
          icon: {
            type: 'emoji',
            value: '🏢',
          },
          order: 17,
          module: 'Timetable',
          parentId: 'timetable',
          roles: ['admin', 'superadmin'],
          isVisible: true,
          isActive: true,
        },
      ],
    },
  ],
};
